name: GrittyBusiness
version: ${version}
description:
  - Lets TNT pulverise Stone through Cobbles and Gravel into Sand.
  - Upcoming - sluices for Sifting particulates

author: Minothor

main: io.github.minothor.GrittyBusiness.GrittyBusiness
api-version: ${spigot.api.version}
load: STARTUP
database: false
